sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: mysql_3RJ7Cn
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5PeFLzsPPT8gG3LPW64
    access-key-secret: U6k1brOZ8gaOIXv3nXbulGTUzy6Pd7
    bucket-name: sky-itcast
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  wechat:
    appid: wx8d154806bca35e37
    secret: 8373bb7b9695e5727b463f4029624631
